deployment:
  tasks:
    - export DEPLOYPATH=/home/hdylfwdk/public_html/
    - /bin/cp -R bootstrap-5.0.2-dist $DEPLOYPATH
    - /bin/cp -R "css files" $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R investment_Docs $DEPLOYPATH
    - /bin/cp -R "js folder" $DEPLOYPATH
    - /bin/cp -R videos $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp construction.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp estate.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH